import { Inter } from 'next/font/google';
import './global.css';
import '@/styles/lib/embla.css';
import '@/styles/lib/deals.css';
import '@/styles/lib/product.css';
import '@/styles/lib/carouselThumb.css';
import Provider from './provider';

const inter = Inter({
  weight: ['300', '400', '600'],
  subsets: ['latin'],
  display: 'block',
  variable: '--font-inter',
});

export const metadata = {
  title: 'Welcome to web-end-user',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="relative flex flex-col min-h-screen">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
