import Layout from '@/components/layouts';

export const metadata = {
  title: 'Welcome to web-end-user',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
