#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Add PATH
export PATH="/usr/local/bin:$PATH"

# Lint the project
yarn lint

# Run tests
yarn test

# Build the project
yarn build

# อัพเดท patch version และสร้าง commit ใหม่
yarn config set version-git-tag false
yarn version --patch
git add package.json
git commit -m "chore: bump version [skip ci]"
