#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Add PATH
export PATH="/usr/local/bin:$PATH"

# Set git config
git config --local user.name "GoGoCash Bot"
git config --local user.email "bot@gogocash.co"

# Lint the project
yarn lint

# Run tests
yarn test

# Build the project
yarn build

# อัพเดท patch version และสร้าง commit ใหม่
npm --no-git-tag-version version patch
git add package.json
git commit -m "chore: bump version [skip ci]"
