#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint the project
yarn lint

# Run tests
yarn test

# Build the project
yarn build

# อัพเดท patch version และสร้าง commit ใหม่
yarn version --patch --no-git-tag-version
git add package.json
git commit -m "chore: bump version [skip ci]"
